### ISSUE TITLE
Implement recording in SDK

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#115]

**Comment by harshithagb** [comment]
Can we read/record the raw audio data while the call is happening?

**Comment by atsakiridis** [comment]
Hi @harshithagb, we currently don't support this in the SDKs as it is supported in the server side so we don't have a concrete use case for it. If you have such a use case, please let us know so that we further discuss it. You could contribute it as well if interested, with our help/guidance of course ;)

From a quick look I see that there's a MediaStream Recording API in Chrome and [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API), so I would assume there would be interfaces exposed in the native webrtc APIs that we could use to make it happen.

**Comment by atsakiridis** [comment]
Server side provides facilites for that so it isn't needed for now
