### ISSUE TITLE
Make Android SDK listening port configurable

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#26]

**Comment by mehturt** [comment]
I see SipProfile.setLocalPort() method, so it is configurable now, isn't it?

**Comment by atsakiridis** [comment]
@mehturt it was configurable but only internally, which was no good. Now that the signaling refactoring is done, it is exposed via RCDevice parameter

**Comment by atsakiridis** [comment]
Fixed with 9232cb20f79e13c416ae5fca598d4fcc1377b241, as part of signaling refactoring activity
