### ISSUE TITLE
Add welcome screen where user picks username and password

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#262]
And optionally registrar. Note that that screen should only show up the first time the user opens the application -then it should save their preference. That will add an extra step for the first time but will make it clearer to the user what credentials they are using and is overall better experience I think.

@deruelle, please let me know if you have any reservations. I'm adding it in BETA4 for now

**Comment by mehturt** [comment]
I'm writing an app based on the hello world example and I did this using preferences (settings). But yes a "welcome" screen would be nice.
Not sure if this issue is relevant for the examples only, or for the SDK.

**Comment by atsakiridis** [comment]
Reopening because I found a bug where if the welcome screen is abandoned before hitting 'Sign Up' and the App is re-opened we get an unrecoverable crash

**Comment by atsakiridis** [comment]
@mehturt sorry missed your comment. This is about the Olympus Application, not the SDK
