### ISSUE TITLE
In some devices using RaaS calls don't work from Olympus

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#271]
I haven't been able to reproduce it myself but some colleagues aren't able to call for example 1235 on RaaS. After investigation it seems that no INVITE reaches Restcomm, while it isn't true for MESSAGEs, which work fine. 

Also the same device that doesn't work for cloud, works for a private instance (port 5080)

**Comment by atsakiridis** [comment]
Got logs from @leftyb where the issue is reproducible:

https://gist.github.com/atsakiridis/939bea1b55e576d79689

And here are logs from a successful scenario in order to diff:

https://gist.github.com/atsakiridis/438d018ff18e0fe16eb1

**Comment by atsakiridis** [comment]
This seems actually Android related. Please refer to this: https://code.google.com/p/android/issues/detail?id=201007

**Comment by atsakiridis** [comment]
As a workaround we can open port 5080 in the Restcomm-Connect side. With that the issue is no longer reproducible.

**Comment by deruelle** [comment]
Did you test using TLS ? I think it's worth a try for those users so we don't have to open specific ports.

**Comment by atsakiridis** [comment]
Oh, right, good catch @deruelle, let me re-open to test once I implement TLS in this release

**Comment by atsakiridis** [comment]
This seems to have been successfully tested by the guys at Locatrix, after TLS was introduced. Closing for now.
