### ISSUE TITLE
In some specific devices we get EPERM when SDK is used with UDP

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#276]
This is the error we get in @leftyb device:

RCConnection error: send failed : EPERM (Operation not permitted)

Currently, we are not using UDP so this is not an issue of the current SDK (using TCP), but let's keep it around just in case in pops in the future

Here's the jain sip log (haven't found any issues in that curiously):

https://gist.github.com/atsakiridis/6dd9c6bf26a730afc36d

**Comment by arslan70** [comment]
Trying to use the SDK and following the steps from http://docs.telestax.com/restcomm-client-android-sdk-quick-start/
Getting the EPERM exception and I'm not sure if the stack is using TCP or UDP(Haven't mentioned in the configuration)
The configuration is pretty straight forward:
            connectParams.put("username", "sip:+1235@<restcomm-ip-address>:5060");
            connectParams.put("video-enabled", false);
            connection = device.connect(connectParams, this); 
**Exception in console while calling:**
E/RCConnection: onSipUAError(): error code: SIGNALLING_CALL_ERRORerror text: sendto failed: EPERM (Operation not permitted)

**Comment by atsakiridis** [comment]
@arslan70 could you check with latest SDK commit see if the issue is fixed? It should use TCP (you can check from https://github.com/RestComm/restcomm-android-sdk/blob/master/restcomm.android.client.sdk/src/main/java/org/mobicents/restcomm/android/sipua/SipProfile.java#L36). IIRC this setting is currently fixed -i.e. not configurable

**Comment by atsakiridis** [comment]
Let's address this is next release together with stability work

**Comment by atsakiridis** [comment]
No longer occuring
