### ISSUE TITLE
Send multiple DTMF

### ISSUE THREAD

**Issue by mehturt** [RestComm/restcomm-android-sdk#286]
I'm using restcomm-android-sdk and I'm wondering what is the proper way to send multiple DTMF.
1. Can I send multiple DTMF digits in one INFO? (e.g. DeviceImpl().GetInstance().SendDtmf("1234");)
2. Can I send multiple DTMF in separate INFO without waiting for the ACK first?

My observation is that neither works properly, but I was not able to find (on Google) how to do this properly.
What worked for me is to send one digit at a time and wait for ACK. Thanks for your input.

**Comment by mehturt** [comment]
The problem with #2 was I think that each INFO was sent with the same cseq, if it was sent before answer was received.  Sometimes I used to receive error instead of successful ack.  But it may be a peer problem as well, I did not find this in specs online.

My current implementation consists of:
- sending DTMF one by one, waiting for ack before the next is sent..
- I added this impl in DeviceImpl
- added new SipEventType.INFO
- catch this in DeviceImpl.onSipMessage
- call SendDTMF() until everything is sent

I can commit this and create pull request, but looking for input whether this approach is OK.

**Comment by atsakiridis** [comment]
Thanks for bringing this contribution forward @mehturt. The issue I see with multiple messages and waiting for each is that it might prove error prone in the long run. I think a more robust solution would be to send all digits in one INFO message as discussed in your [stackoverflow question](http://stackoverflow.com/questions/36592981/multiple-dtmf-digits). Which means putting the digits one after the other in the INFO body. Should be pretty straight-forward to implement. What do you think? Want to take a crack at it?

By the way who is the receiver of the DTMF? Cause different servers might have different behaviour.

Regarding the cseq issue, this seems very weird, would be interested to have a look at it, can you share a tcpdump capture file?

**Comment by mehturt** [comment]
Yes, I will implement the "one after the other in one INFO" as you suggest, it would be good if it worked that way. Anyway it would be good if you could point out some kind of SIP spec where this behavior is defined, if it is defined at all.
My receiver is a 2n IP intercom, www.2n.cz

**Comment by mehturt** [comment]
[dtmf.txt](https://github.com/RestComm/restcomm-android-sdk/files/220576/dtmf.txt)
Here is the log of sending multiple INFO back to back, I'm seeing Internal server error answers to some of them, also the cseq seem messed up, not in sequence.

**Comment by mehturt** [comment]
Trying the other way, sending multiple DTMF in one INFO results in successful response, but does not do what it's supposed to do on the other end, so not sure if the other end understands this correctly:
[dtmf2.txt](https://github.com/RestComm/restcomm-android-sdk/files/220639/dtmf2.txt)

**Comment by atsakiridis** [comment]
@mehturt just checked the dtmf.txt and indeed the Cseq seems to be the same among two consecutive requests in the same dialog which is weird. I assume you have an active call when you send the DTMF, right? Could you please open a separate issue for that and add the log there as well?

**Comment by atsakiridis** [comment]
@mehturt: also checked dtmf2.txt and response seems ok, I wonder if you SIP server is having issues parsing it properly. Been looking around for a spec for that but haven't found any :(. Seems like it's not that standardized

**Comment by mehturt** [comment]
I just created issue 290

**Comment by atsakiridis** [comment]
Great thanks

**Comment by mehturt** [comment]
The implementation that works for me (sending one digit in DTMF at a time) can be seen here
https://github.com/mehturt/restcomm-android-sdk/tree/dtmf

**Comment by mehturt** [comment]
Could we use Dialog.incrementLocalSequenceNumber() before creating each INFO message?

**Comment by atsakiridis** [comment]
@mehturt I think cseq should be handled automatically by the stack, but let me have a better look at it and your work and I'll get back to you next week

**Comment by atsakiridis** [comment]
@mehturt we have refactored the signaling stack to make it fully asynchronous during last summer and I recall that we did some fixes for the Cseq as well, so it should work now. Can you retry?

Closing for now, feel free to reopen if the issue persists
