### ISSUE TITLE
Cseq is the same when not waiting for server response

### ISSUE THREAD

**Issue by mehturt** [RestComm/restcomm-android-sdk#290]
Value of cseq is not updated when request is sent without waiting for response.
This could be seen e.g. when multiple DTMF are sent without waiting for response.
See issue 286 [https://github.com/RestComm/restcomm-android-sdk/issues/286](url) , [https://github.com/RestComm/restcomm-android-sdk/files/220576/dtmf.txt](url)

**Comment by atsakiridis** [comment]
@mehturt: indeed there were issues with Cseq in old signaling stack. Now the media stack has been written from scratch so all of those should be fixed. Once BETA4 comes out I'll try to ping you so that you can retry

**Comment by atsakiridis** [comment]
@mehturt as noted in the other issue, the new stack is out for some time now, so please use latest release from GitHub, it should work
