### ISSUE TITLE
Test audio & video logic in SDK

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#311]
We need to make sure that the local media remains independent of the remote. So for example a call that is made by SDK as audio can be answered as video, which means that the local party won't be sending video, but the remote party will be sending video back.

**Comment by atsakiridis** [comment]
Turns out that the PeerConnectionClient object we use (takes from AppRTCDemo) doesn't allow for that. Instead, you just configure whether the call is audio or video based on how you make or accept a call. The peers preference isn't taken into account here.

Hence this needs some development effort to change that logic and make the 2 videos configurable independently.

**Comment by atsakiridis** [comment]
Deferring this to BETA5, @deruelle please let me know if you have any concerns

**Comment by deruelle** [comment]
@atsakiridis makes sense to defer

**Comment by atsakiridis** [comment]
This is duplicate of #598 where I have already analyzed some challenges. Let's use that
