### ISSUE TITLE
Enabling Wifi after being offline causes issues in binding

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#442]
The issue seems to be that when OS notifies us that Wifi is available and try to retrieve the current active IP from OS 0.0.0.0 is returned, which of course fails. 

Adding a timeout to delay retrieving current active IP it works fine, which is very strange

**Comment by atsakiridis** [comment]
After various attempts I couldn't make it work, tried retrieving the wifi address using network interfaces API, but still got the same issue. Asked on SO: http://stackoverflow.com/questions/40107319/networkinfo-isconnected-returns-true-but-not-able-to-retrieve-interface-ip-ad

**Comment by atsakiridis** [comment]
Never managed to reproduce it. Let's close for now

**Comment by ForGuru** [comment]
@atsakiridis I have faced issue like this when switching to WiFi from Data, Connection Established Successfully but When I dial a number it stuck there and I don't see any invite message on Server.

Its Strange

**Comment by atsakiridis** [comment]
@ForGuru please try to include logs for your issues, so that we can make troubleshooting faster. We need to be able to check the exact circumstances for your issue to push the investigation forward.
