### ISSUE TITLE
libjingle_peerconnection_java.jar file missing in libs folder

### ISSUE THREAD

**Issue by ravindra-d** [RestComm/restcomm-android-sdk#444]
Hi,
I downloaded the code, but couldn't find the libjingle_peerconnection_java.jar under restcomm.android .sdk directory.
Please attach jar file.

**Comment by atsakiridis** [comment]
Hello, the jar should be there in latest release restcomm-android-sdk-1.0.0-beta4.tar.bz2, maybe you downloaded the wrong bundle?
