### ISSUE TITLE
RCConnection Error: Connection Timedout (Media)

### ISSUE THREAD

**Issue by ForGuru** [RestComm/restcomm-android-sdk#446]
This error appears on Android Samsung Galaxy S6 edge 6 Edge. I think the issue is with Libjingle.so files because its working on other phones below avmv8

It appears only when Answering a Call while dialing call doesn't dial out.

Do you recommend good source of compiled libjingle ?

**Comment by atsakiridis** [comment]
@ForGuru can u please attach Android Studio logcat from the problematic scenario?

**Comment by ForGuru** [comment]
Currently I don't have ARMV8 phone with me . I have it working on ARMV7 android phones but people who tested on ARMV8 reported this issue. 

LibJingle library from AppRTC project.

**Comment by atsakiridis** [comment]
Armv8 should be backward compatible, so I'm not sure that's the issue. Unfortunately I don't have armv8 phone either so to figure out what is going on we need more data.

Sadly there aren't official libjingle libs from Google yet. So for now everyone in need, needs to build from scratch.

**Comment by ForGuru** [comment]
I am recompiling lib jingle and using this guide 
https://github.com/pristineio/webrtc-build-scripts
Will it work ?? What you think?

I will be able to get armv8 tomorrow to test.
Actuall error message is 
"RCConnection Error"
Connection Times out (media)

While dialing video call on such devices we don't get Local Video As well

**Comment by ForGuru** [comment]
I have recompiled and received following 
libjingle_peerconnection.jar
libjingle_peerconnection_so.so files 

but faced an other issue 

videoSource.stop();
videoSource.restart();
 videoCapturer.onOutputFormatRequest(width, height, framerate);
videoSource.restart();

Were not there ?? What to do any idea ??

Do you have any specific release ??

**Comment by atsakiridis** [comment]
Could be that Google updated some APIs. Any chance you tested with armv8?

**Comment by ForGuru** [comment]
Currently pulled this code 
https://github.com/njovy/AppRTCDemo

and I used Lib Jingle provided there but still needs to test on armv8. Will let you know on this

**Comment by ForGuru** [comment]
After this update I am able to make Video Call with Oneplus 3 user which is a ARMV8 devices 

Will post other results

**Comment by atsakiridis** [comment]
Great, yes please do so that we are are to get to the bottom of this. Also, are you using Restcomm Olympus App and modified the jar + .so for libjingle peer connection?

**Comment by ForGuru** [comment]
Issue solved with new .so files and .jar file from above link 

Thanks :)

**Comment by atsakiridis** [comment]
@ForGuru thanks for posting back. I would still be interested to see the logcat from the problematic scenario, is it possible to paste it in a gist?

Also the link you pasted above seems to refer to webrtc revision #13665, but is this the actual revision of the build you used successfuly? Because #13665 is a couple of months old already.
