### ISSUE TITLE
Investigate why call was allowed even though connectivity is off 

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#456]
https://app.testfairy.com/projects/1897533-restcommolympus/builds/4635482/sessions/89

**Comment by atsakiridis** [comment]
It seems that for some reason Henrique's nexus lost connectivity at some point (no registers coming in and all options towards that failing) some minutes before the call. Actually that is what happened cause I just checked the wifi signal for his device and it drops right before the call. So the question is why was he allowed to make the call and not got a notification that there's no networking instead.

The only plausible explanation here is that for some reason when Wifi came back online for some reason the REGISTER messages didn't resume.

Unfortunately, once more there are missing logs in TF and I can't tell when and why REGISTER messages seize to be sent. According to android logs no REGISTER is ever sent, while, according to Restcomm logs we do have REGISTER properly sent and processed ~5 minutes before the call.

**Comment by ForGuru** [comment]
I have experienced that sometime when phone is in sleep mode SDK gets unregister from server and server doesn't have the registration of device but device assumes that its still registered and it tells online.

Is it the same issue ?

**Comment by atsakiridis** [comment]
@ForGuru how does the android SDK get unregistered from the server? Can elaborate on that? Also do you have client/server logs that we can discuss on? Cause by default the SDK should continue to register with the server indefinitely (even when Olympus App is in the background)

In our case it seems that loss of connectivity on the Android side is caused unwanted side effects.

**Comment by atsakiridis** [comment]
Tried to open many Apps in the device, or to force the memory to increase to achieve memory pressure, among other things, but to no avail. Also tried to kill the App from Android Device Monitor as described [here](http://debuggingisfun.blogspot.gr/2014/12/android-simulate-low-memory-kill.html), but in that case trying to open the App and making a call after that indicates that RCDevice is offline

Opened a discussion at Android Development G+ community

**Comment by atsakiridis** [comment]
No longer reproducible
