### ISSUE TITLE
Read audio data during an ongoing video call

### ISSUE THREAD

**Issue by harshithagb** [RestComm/restcomm-android-sdk#480]
Hi @atsakiridis,

I want to read the audio bytes during an ongoing webRTC video call for some processing. Since microphone is being used by the webRTC I am unable to read from it for my audio processing since mic is not shared in Android.  How can we get just the audio data from the MediaStream or AudioTrack?

**Comment by atsakiridis** [comment]
Let's continue this discussion at https://github.com/RestComm/restcomm-android-sdk/issues/115, to have everything in one place
