### ISSUE TITLE
Upload SDK to sonatype from CI/CD facilities

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#491]
Notice that this should happen if IT pass and we are in master branch, which is deemed production ready.

This already works locally without issues. We need to upload from Travis which has a lot of additional impacts like securely installing all resources at Travis machine and performing upload.

Also need to change from snapshot to using staging repository and also releasing if all checks are ok

**Comment by atsakiridis** [comment]
This is 2 steps:
1. Upload from local machine which has been fixed
2. Upload from Travis which has additional impacts like securely installing all resources at Travis machine and performing upload

**Comment by atsakiridis** [comment]
Also lets introduce functionality to upload libwebrtc.aar to either sonatype (maybe using third-party repository, if possible), or to artifactory. This needs to be introduced both locally and for Travis.

**Comment by atsakiridis** [comment]
As a first step lets manually upload libwebrtc to artifactory whenever there are changes because an actual full flown webrtc build won't be possible in Travis. Also since Google is working on supporting this not sure if it would make sense to spend the time to add an internal CI job (this would also have it's challenges as a huge partition is needed for the build).

@deruelle wdyt?

**Comment by deruelle** [comment]
Agreed.
