### ISSUE TITLE
Migrate Olympus code to separate GitHub repo

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#495]
That will also help us identify pain points and streamline the integration of our SDK into a third party Android App kept in a separate repo. Remember to add proper separate versioning in Olympus; notice that up to now we are using the version number for SDK + App (this is problematic because version increases for the SDK even when an Olympus-only change has been made)

**Comment by atsakiridis** [comment]
Actually using a single repo for both doesn't help in that because it's tough to monitor if a change only affecter the App or the SDK. Maybe we should keep android olympus in a separate repo from the SDK. @deruelle what do you think?

**Comment by deruelle** [comment]
makes sense. It's already this way for web. Here you go: 

- https://github.com/RestComm/olympus-android 
- https://github.com/RestComm/olympus-ios

**Comment by atsakiridis** [comment]
Exactly, thanks @deruelle

**Comment by atsakiridis** [comment]
Making this an Epic as it is a big chunk of effort where we need to consider changes in CI/CD, testing, etc

**Comment by atsakiridis** [comment]
For now we 're not investing on client features; let's close this as it will also contribute to overhead
