### ISSUE TITLE
Enabling video leaves the library useless

### ISSUE THREAD

**Issue by vivek1794** [RestComm/restcomm-android-sdk#508]
Hi,

I am using restcomm library along with our own personal infrastructure based on freeswitch. It works perfectly fine when audio alone is enabled behind NAT. When video is enabled, ice connection remains in "checking" state and hence onCallTimeout is triggered. Is there any issue regarding video calls? Since audio works fine, it shouldn't be an issue with video right?

**Comment by atsakiridis** [comment]
Hi @vivek1794, yeah video should be working out of the box. 

Please share Android full logcat for your scenario so that we can have a look.

**Comment by vivek1794** [comment]
Have attached the logs. When video is enabled, the onIceConnected event is not triggered and hence the call gets terminated after 15 seconds (specified as CALL_TIMEOUT_DURATION_MILIS). The same code, when the video is disabled, works perfectly fine and the onIceConnected event is triggered.

[webrtc_video_logs.txt](https://github.com/RestComm/restcomm-android-sdk/files/738631/webrtc_video_logs.txt)

**Comment by atsakiridis** [comment]
@vivek1794 that is strange. I see signaling exchanged and seems ok, I wonder though why the client doesn't use reflexive candidates and only uses local and relay. Maybe very restrictive NAT? Still it wouldn't explain how come audio only calls work, although it could explain a delay in the setup time.Your server seems to be in a public ip right? Cause I only see host candidates. 

You could try to increase the timeout from 15 seconds to something bigger, like 30 to see if it makes any difference and if its a matter of not having the time to finish with STUN checks (though 30 seconds is a very high value). You could also gather traffic in both ends to see if the STUN checks fail for some reason.

Hope this helps

**Comment by vivek1794** [comment]
@atsakiridis Thanks a lot for the reply.

Yes, we are under a very restrictive NAT. But this issue occurs in networks with less restrictive NAT as well. Our server is using a public IP address. 

I have removed the onCallTimeout() method call so that there is no time limit. It doesn't connect even after 2 minutes. Audio seems to be working fine in this scenario (when callTimeout is removed and video call is enabled) while video transfer is not working at all. I am attaching the logs for audio only/audio video calls made in both lenient and restrictive NAT. 

Your help in this regard is highly appreciated

P.S: I tried subscribing for restcomm services through "Try it now" button in your website. I am yet to get any response from your end. 


[audio_only_lenient_nat.txt](https://github.com/RestComm/restcomm-android-sdk/files/756714/audio_only_lenient_nat.txt)
[audio_only_restrictive_nat.txt](https://github.com/RestComm/restcomm-android-sdk/files/756713/audio_only_restrictive_nat.txt)
[audio_video_lenient_nat.txt](https://github.com/RestComm/restcomm-android-sdk/files/756715/audio_video_lenient_nat.txt)
[audio_video_restrictive_nat.txt](https://github.com/RestComm/restcomm-android-sdk/files/756716/audio_video_restrictive_nat.txt)

**Comment by atsakiridis** [comment]
@vivek1794 seems that for the problematic scenario ICE never transitions to connected, which probably means that STUN connectivity checks between pairs fail. Like I said previously I think you need to collect traffic, specially in the client side and see what happens with STUN connectivity checks. You should see packets between client and server candidates and see if there any failures there and why. Let us know if we can further assist.

On the 'Try it now' issue we 're checking it, thanks for reporting

Best regards,
Antonis

**Comment by vivek1794** [comment]
@atsakiridis I tried capturing STUN packets and I see no issue there. But when I enable audio and video, I receive "Received STUN ping response" message once in the log and then "Timed out after 15030 ms without a response, rtt=3000" for other one. If STUN is issue, Audio shouldn't be working right? 

When I check with 3G/4G, I do get srflx candidates but it doesn't help either. I am not able to get video to work properly. Is it possible for you to share the latest webrtc so files that are being used?

**Comment by atsakiridis** [comment]
@vivek1794 could you maybe share .pcap so that I can have a look as well?

The webrtc library files we use are part of our latest [release](https://github.com/RestComm/restcomm-android-sdk/releases/download/v1.0.0-BETA4/restcomm-android-sdk-1.0.0-beta4.tar.bz2). Notice that they are a couple of months old

**Comment by vivek1794** [comment]
Hi @atsakiridis,

Have uploaded the pcappng file as zip. Yes I am using the same webrtc library files. As you can see, I have continuous audio transfer, while video transfer is not working at all. (I have removed the onCallTimeout method to make sure that the session is not closed before the ice candidates have time to connect - even after 2 minutes, the ice candidates never transition to COMPLETED state. It remains in CHECKING state)

[webrtc_logs.pcapng.zip](https://github.com/RestComm/restcomm-android-sdk/files/789190/webrtc_logs.pcapng.zip)

**Comment by atsakiridis** [comment]
@vivek1794 sorry for the delay, been very busy with high priority assignments. Ok so I checked your .pcap but seems that all STUN requests are unanswered. Are you sure you gathered the full scenario? I also don't see the webrtc DTLS handshake.

**Comment by atsakiridis** [comment]
Closing after long period of inactivity. Feel free to reopen if issue persists
