### ISSUE TITLE
Olympus's gradle build failing

### ISSUE THREAD

**Issue by ionicc** [RestComm/restcomm-android-sdk#588]
Olympus is failing to build its gradle with this log.

Dumping the error log below

`Error:(50, 0) Could not get unknown property 'TEST_RESTCOMM_ACCOUNT_SID' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=18, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=25, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=UNOFFICIAL, applicationId=org.restcomm.android.olympus, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={TEST_RESTCOMM_LOGIN=com.android.builder.internal.ClassFieldImpl@7ad9ce49, TEST_RESTCOMM_PASSWORD=com.android.builder.internal.ClassFieldImpl@7bcf91a2}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
<a href="openFile:Z:\GitHub Projects\restcomm-android-sdk\Examples\restcomm-olympus\app\build.gradle">Open File</a>`

**Comment by atsakiridis** [comment]
Fixed with #589
