### ISSUE TITLE
Provision of logging out

### ISSUE THREAD

**Issue by codezoned** [RestComm/restcomm-android-sdk#593]
Consider adding a logout button. The only way to get to the login activity is by clearing the cache that I've found yet.

**Comment by atsakiridis** [comment]
Actually this is a good idea by itself (i.e. not as part of #388). Right now there are times when you want to stop refreshing registrations with Restcomm Connect as part of a test or whatever. And the only way to do that is to kill the Olympus App which isn't very nice. 

We just need to figure our the UI/UX of this functionality to make sure we don't clutter things up

**Comment by atsakiridis** [comment]
Deferring it to 2.0 as its not critical

**Comment by atsakiridis** [comment]
With push notification introduction this happens whenever we leave the App, so it should be enough
