### ISSUE TITLE
Transport other than TCP or TLS

### ISSUE THREAD

**Issue by WolandPL** [RestComm/restcomm-android-sdk#602]
Is there a way to use WebSocket as transport? In jainSipClientBind method in org.restcomm.android.sdk.SignalingClient.JainSipClient I can see:

```
String transport = "tcp";
if (JainSipConfiguration.getBoolean(configuration, RCDevice.ParameterKeys.SIGNALING_SECURE_ENABLED)) {
            transport = "tls";
            //transport = "wss";
}
```

looking like you tried or plan to implement WebSockets, but currently it's not available. Is this right?

**Comment by atsakiridis** [comment]
Should be working @WolandPL. Jain SIP stack that runs underneath supports it and I tested it a couple of months back; just uncomment wss instead of tls ;)

**Comment by WolandPL** [comment]
Should ws also work instead of TCP for non-secure?

And by the way - earlier I tried to change some of your code in the SDK but my project still uses pre-build jar, so my changes in your code don't make any effect. How do I force using changed SDK code instead of jar build earlier?

**Comment by WolandPL** [comment]
I did uncomment wss and I get WSS in VIA header and "transport" in CONTACT header, but server still seems not to recognize it as a websocket traffic. Are you sure setting transport to WSS is enough to really send REGISTER to WebSocket? I tried adding "wss://" at the beginning of Signaling Domain but then it fails valdiation (and I saw exactly that - wss://... as a registrar in your javascript library. Maybe that's the problem?

**Comment by atsakiridis** [comment]
@WolandPL just tried again with WSS and it is working fine. You must not add wss:// in the beginning of signaling domain. For example in my case domain is:

```
cloud.restcomm.com:5063 
```

Notice that I had to explicitly use port 5063 in our case since the WSS port is 5063. If with these changes you still get issues, please share more information like android logcat
