### ISSUE TITLE
Not possible to use Android ringtones as notification sounds

### ISSUE THREAD

**Issue by WolandPL** [RestComm/restcomm-android-sdk#624]
It's possible to use raw sound resource files as notification sounds, but not possible to use standard Android ones.

It would be if there's a possibility to pass an URI to the ringtone as RESOURCE_SOUND_RINGING (or maybe a new parameter). Currently there's URI creation hardcoded in RCDevice:

`NotificationCompat.Builder builder =
            new NotificationCompat.Builder(RCDevice.this)
...
.setSound(Uri.parse("android.resource://" + getPackageName() + "/" + audioManager.getResourceIdForKey(ParameterKeys.RESOURCE_SOUND_RINGING)))`

**Comment by atsakiridis** [comment]
Interesting idea @WolandPL :). How would  you model the SDK's API to accommodate for that? Would you like to come up with a proposal?

**Comment by WolandPL** [comment]
I already have a working prototype. In my version all the sounds can be either set as int (resource id) or String (Uri). Format is dynamically detected and appropriately handled. I can push my code if you'd like me to. I would just need some guidance, because I've never contributed to such project.

**Comment by atsakiridis** [comment]
Hi @WolandPL, any chance you worked on the PR yet?

Thanks

**Comment by WolandPL** [comment]
Not yet, sorry. I would need to refactor my code a bit to make it official but haven't got the time yet.

**Comment by atsakiridis** [comment]
Sure no problem, take your time, and if you have any questions you know where to find us ;)

**Comment by atsakiridis** [comment]
Hi @WolandPL, did you get a chance to follow up on this?

Thanks,
Antonis

**Comment by WolandPL** [comment]
Sorry, still didn't have time and I won't have in upcoming weeks. Please feel free to close this ticket if you don't want it to stay open for so long.

**Comment by WolandPL** [comment]
@atsakiridis I'd like to ask you a question not related to this thread, but it seems that GitHub doesn't have private messaging. How can I send it to you?

**Comment by atsakiridis** [comment]
@WolandPL sorry for the delayed response, was on vacation and then pretty busy with backlog. You can send either on Restcomm-discuss Gitter channel if you want: https://gitter.im/RestComm/Restcomm-discuss, or if you want to reach me privately text me on Gitter, username: atsakiridis

**Comment by atsakiridis** [comment]
@WolandPL closing this as I haven't received reply in long time. Please feel free to reopen
