### ISSUE TITLE
Consider enforcing policy for ICE candidate timeouts

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#684]
Seems that with Chrome 58+ the timeout of candidates is [increased](https://bugs.chromium.org/p/webrtc/issues/detail?id=7844#c3) from 10 seconds to 40 seconds. This means that if we are on a device where any weird interfaces are up (i.e. VPN, etc). The user might end up waiting a loooong time until the call is connected.

There are 2 obvious solutions:
- Implement Trickle ICE
- Enforce policy inside SDK so that if we have the candidates we need we can timeout sooner and establish the call.

Now, since this is not something that is bitting us yet, it's not critical. But we definitely need to keep an eye on it. Here are some interesting resources:
- WebRTC [issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=7844)
- [Thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/j595lLysVYI/RKelBkFACwAJ) in webrtc-discuss

For now I'm assigning some time to properly investigate and see how we can approach this without messing things up, as a spike. If needed we can follow up

**Comment by marca56** [comment]
@atsakiridis ... since it's not urgent from a delivery perspective, I would focus on the trickle ICE approach because it's the best technical solution.

**Comment by atsakiridis** [comment]
@marca56, right, trickle is the right way to go in the long term. However there's a chance that we get issues in the field soon (actually I think we have already got some in the past but I wasn't able to repro) and I want to make sure we have a workaround in case of emergency. So yeah no plans to act on this for now. Let's see how this goes.

**Comment by atsakiridis** [comment]
Indeed we have been getting this a lot lately both from within the team and outside, so let's bump priority

**Comment by marca56** [comment]
@atsakiridis , agreed. Let's see if we can work on both IOS and Android for this. There are a lot of important users on IOS, including our CEO ;)

**Comment by atsakiridis** [comment]
After discussion with the team we are going with the following workaround until Trickle ICE is ready:
- Provide a timeout setting both Olympus Settings as well as RCConnection configuration
- Possible values are 'No timeout', '3 seconds', '5 seconds', etc
- 'No timeout' means previous behavior and the user needs to wait for onGatheringComplete event, and if there are any issues with used network interfaces, the webrtc timeout is 40 seconds
- Selecting any of the other values means that the SDK will wait that amount of time and after that go ahead with the call with whatever candidates it managed to collect
- Default value is 'No timeout'
