### ISSUE TITLE
Test SMS link to launch by intent (SDK app) an audio or video call

### ISSUE THREAD

**Issue by marca56** [RestComm/restcomm-android-sdk#691]
* send SMS from SDK app to another user including a link to launch WebRTC audio or video call;
* if user does not have SDK app installed, will launch TestFairy to download the SDK;
* if user has SDK app installed, will launch or come to foreground and dial the sender for audio or video call;
* would be nice to show a link preview like our RestcommONE logo and either audio or video icon if possible;

**Comment by atsakiridis** [comment]
@marca56 as discussed I already tested this, as well as added an enhancement to get it working for your use case of links in an SMS. But notice it doesn't cover the full 'requirements' you laid out here:

- The App is not installed if not available on the device
- No preview is available
- The call defaults to video call

If we want the full thing we need to re-iterate, but I'd suggest doing that post 1.0. Also to get this done properly we need to properly support: [deep links](https://developer.android.com/training/app-links/index.html#web-assoc). With proper support we are not longer bitten by the issue of the issue getting plagued by defaults. The user gets navigated without ambiguity and the whole thing should work super smoothly.

What do you think? Should I create a separate issue and plan post-1.0 GA?

**Comment by marca56** [comment]
@atsakiridis for the purpose of the demo needed, we are fine; I agree we should create a story and plan to update on both Android and IOS after 1.0 GA

**Comment by atsakiridis** [comment]
@marca56 ok, opened https://github.com/RestComm/restcomm-android-sdk/issues/693 for later
