### ISSUE TITLE
Use google's official webrtc artifact

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#707]
So far we have been building our own or pulling the .aar from their build system. Now that they provide it via maven let's use [it](https://bintray.com/google/webrtc/google-webrtc#)

Notice that we should probably not use the wildcard coordinates suggested [here](https://webrtc.org/native-code/android/):

```
compile 'org.webrtc:google-webrtc:1.0.+'
```

As there are often breaking changes from one version to the next and we'll have bad surprises.

Notice that I'm making this a spike as there might be 0 changes (if no changes have occurred in the API since our current version) to a lot of them (if API changes have occurred). So let's investigate and create new issue if needed to actually tackle this

**Comment by ElAmin88** [comment]
Hello ,  where can i find the new list of the API as i can't initialize a new PeerFactory ?

**Comment by atsakiridis** [comment]
Done

**Comment by atsakiridis** [comment]
@ElAmin88 can you elaborate what you are trying to do here? Why do you need to initialize a PeerFactory? This should be handled by the SDK internally
