### ISSUE TITLE
REGISTER Received SIP response 403 Forbidden

### ISSUE THREAD

**Issue by lvsj** [RestComm/restcomm-android-sdk#730]
[log.txt](https://github.com/RestComm/restcomm-android-sdk/files/1426455/log.txt)
Happened to this issue,when i first run app to register . Is anyone has the same problem?

**Comment by atsakiridis** [comment]
@lvsj you need to check your credentials. The problem is that the server doesn't know the username/password combination you provide

**Comment by lvsj** [comment]
Sorry, i do not understand what do you mean to check my credential, how to check?  Could you give more details.BTW, i just fork this repo  and do not modify any code.

**Comment by atsakiridis** [comment]
@lvsj replied to your other enquiry in Gitter. Please let me know if you 're still having issues. Closing this issue for now; feel free to reopen
