### ISSUE TITLE
Seems that WSS transport causes a crash when DNS SRV is used

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#744]
When I tried with code prior to DNS SRV all is good, so something there is messing things up. Maybe it's SDK code we introduced back then

This is not currently critical in the sense that right now we are using regular TLS for secure signaling, but need to fix it as it will help with connectivity issues.

Notice that I have done some tests prior DNS SRV was introduced on branch `testWss`

@ognjenns ping me so that I let you know how to enable WSS

**Comment by domimod** [comment]
If I understand correctly WSS is currently totally unusable?
Do you have an estimate when this issue would be corrected?

**Comment by atsakiridis** [comment]
@domimod I'm afraid I can't give you an accurate estimate at this point as we 're currently using TLS (ie over TCP) and actually we never got a chance to put WSS in production although it definitely is on the roadmap for later this year. As described above seems that this broke when we introduced DNS SRV functionality.

If you are interested in taking a stab at it and contributing it, let us know and we 'll be happy to assist you ;)

**Comment by WolandPL** [comment]
Should WebSocket (unsecure) be working? I cannot connect with our server but not sure if this is because of SDK or server configuration.

Do I even configure SDK to use websockets anyhow or is it detected automatically? I tried simply ip:port and SIGNALING_SECURE_ENABLED = false. Should that work with WS?

**Comment by atsakiridis** [comment]
@WolandPL I really couldn't say if insecure WS would work. Can you try? To do that you can change 'tcp' for 'ws' [here](https://github.com/RestComm/restcomm-android-sdk/blob/8f51ba3b252043720e5fe3985f1c047466493cef/restcomm.android.sdk/src/main/java/org/restcomm/android/sdk/SignalingClient/JainSipClient/JainSipClient.java#L438), so that insecure connections use WS instead of TCP

**Comment by WolandPL** [comment]
@atsakiridis I tried WS as transport. It fails with "bad transport" exception. After some debugging I found out that:

createMessageProcessor() method in OIOMessageProcessorFactory class called from
createMessageProcessor() method in SIPTransactionStack class called from
createListeningPoint() method in SipStackImpl class called from
jainSipClientBind() method in JainSipClient class

simply doesn't accept WS (nor WSS). It handles only UDP, TCP, TLS and STCP. For any other transport it throws new IllegalArgumentException("bad transport")

**Comment by WolandPL** [comment]
@atsakiridis I fixed the previous problem by using different MessageProcessorFactory, but now I'm facing a harder one.

DefaultDNSServerLocator seems not to support websockets at all. Just take a look at its getDefaultTransportForSipUri() method - it only mentions TLS, UDP and TCP

**Comment by WolandPL** [comment]
@atsakiridis Most probably I solved this issue. Already tested for WS, need a server side verification for WSS (our server doesn't respond, but REGISTER request is successfully sent from the app). When I have the final confirmation I can contribute.

**Comment by gsaslis** [comment]
@WolandPL thanks for reporting back!  <3 

that would be awesome if you could help out with contributing a fix for this issue!!  🎉 

Plz feel free to let me or @atsakiridis know if you need any help!  ; )

**Comment by atsakiridis** [comment]
@WolandPL any chance you got confirmation on your issue?
