### ISSUE TITLE
AsyncHttpClient and loopj

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-android-sdk#747]
Update the current HttpURLConnection with AsyncHttpClient

**Comment by atsakiridis** [comment]
@ognjenns before doing the change, can you verify that AsyncHttpClient can be easily configured to work with self-signed server certificates? Reason we need that is for testing in staging environments where the server might not have a legit, non self-signed certificate

**Comment by ognjenns** [comment]
We are using the sync calls to server inside the async task; so we dont need this anymore.
