### ISSUE TITLE
Rebrand from Olympus to Restcomm WebRTC Demo

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#766]
- Change icons and texts from Restcomm Olympus -> Restcomm WebRTC Demo
- Home screen from Restcomm Olympus -> Restcomm WebRTC Demo
- Fix the About screen to show as an example 'Restcomm WebRTC Demo 1.0.0-BETA6#1'
   - Also add flavour if possible

**Comment by ognjenns** [comment]
We should change the icon, UI elements, home screen and application name
