### ISSUE TITLE
Do more manual testing for Push Notifications

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#789]
Once all push notifications features are finished we need to test:

- Basic test scenarios as described [here](https://docs.google.com/spreadsheets/d/1gkSJ4libggfKoPcqH9Qv0uQol2A9atirbf4ztKf7vUw/edit#gid=0)
- More edge case scenarios for Push Notifications like (don't forget to add them to the spreadsheet above):
   - Receiving a call while already on call: 1 test when app is on the foreground and 1 when it's on the background. Make sure that in both cases caller gets busy
   - Receiving multiple text messages when the app is in the background, on after the other in varying intervals, like 1, 2, 3, 5, 7, 10 seconds. We can use Restcomm to trigger messages using REST. The idea here is to make sure that the current logic we employ involving using SIP signaling for actual message delivery along with REGISTER/unREGISTER is watertight and the state isn't messed up.
   - ...
- Do a meticulous review of UI/UX with push notifications in mind and make sure all is good. Also test with locked screen. Also test with Oreo notifications and make sure all works as expected

Important: I think it makes sense to use staging for testing, and also use a bigger timeout in RC/Push Server like 5-10 seconds so that we don't have the problems with sometimes notifications not working. That we we can have a stable env to test and if something goes wrong we know it's an issue

**Comment by atsakiridis** [comment]
@ognjenns not sure if we already discussed it, but please add to the spreadsheet any new manual test cases that you think of, to test push notifications, so that we don't forget to test them in future test sessions

**Comment by ognjenns** [comment]
For the staging, I couldnt connect (REGISTER), so I switch to cloud testing. I tested with double calls (one for running the service, second to get actual call while on background) same for messages. We can test this again when we fixes that issue about the timeout.
