### ISSUE TITLE
Investigate disconnect issues

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-android-sdk#808]
Check row 12, 20, 21 in the [TC sheet](https://docs.google.com/spreadsheets/d/1gkSJ4libggfKoPcqH9Qv0uQol2A9atirbf4ztKf7vUw/edit#gid=0)

These are most likely server side issues so we need to:
- Check logcat for signaling messages and see if all is good there
- If not and it's our issue need to fix it
- If not our issue need to open issue in ZD for VVS squad to check

**Comment by ognjenns** [comment]
Its a server side issue, zendesk ticket:
https://telestax.zendesk.com/agent/tickets/35203
